apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-python
  namespace: argocd
spec:
  project: training-project
  source:
    repoURL: https://github.com/karlosv01/modulo2-tema-4.git
    targetRevision: HEAD
    # TODO ejercicio 3:
    # Ajustar al path exacto del componente Python.
    path: project-skeleton/k8s/04-apps/python
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
